ARG build_type
FROM ghcr.io/confidential-clusters/buildroot AS builder
ARG build_type
WORKDIR /compute-pcrs

COPY Cargo.toml Cargo.lock .
COPY rv-store rv-store
COPY compute-pcrs/Cargo.toml compute-pcrs/

# Set only required crates as members to minimise rebuilds upon changes
# For debug builds, build dependencies to avoid full rebuild
RUN sed -i 's/members =.*/members = ["compute-pcrs", "rv-store"]/' Cargo.toml && \
    git clone --depth 1 https://github.com/confidential-clusters/reference-values && \
    if [ "$build_type" = debug ]; then \
        mkdir compute-pcrs/src && \
        echo "fn main() {}" > compute-pcrs/src/main.rs && \
        cargo build -p compute-pcrs && \
        rm -rf target/debug/.fingerprint/compute-pcrs-*; \
    fi

COPY compute-pcrs/src compute-pcrs/src
RUN cargo build -p compute-pcrs $(if [ "$build_type" = release ]; then echo --release; fi)

FROM quay.io/fedora/fedora:42
ARG build_type
COPY --from=builder "/compute-pcrs/target/$build_type/compute-pcrs" /usr/bin
COPY --from=builder /compute-pcrs/reference-values /reference-values
