# SPDX-FileCopyrightText: Jakob Naucke <jnaucke@redhat.com>
#
# SPDX-License-Identifier: CC0-1.0

# This rule is not used by the project cocl-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to confidential-clusters.io resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: cocl-operator
    app.kubernetes.io/managed-by: kustomize
  name: confidentialcluster-viewer-role
rules:
- apiGroups:
  - confidential-clusters.io
  resources:
  - confidentialclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - confidential-clusters.io
  resources:
  - confidentialclusters/status
  verbs:
  - get
