apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: coreos-trustee
spec:
  runStrategy: Always
  template:
    metadata:
      annotations:
        kubevirt.io/ignitiondata: |
          {
            "ignition": {
              "config": {
                "merge": [
                  {
                    "source": "http://register-server.confidential-clusters.svc.cluster.local:8000/ignition-clevis-pin-trustee"
                  }
                ]
              },
              "version": "3.5.0"
            },
            "passwd": {
              "users": [
                {
                  "name": "core",
                  "sshAuthorizedKeys": [
                    "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCWvljBdqqjHvIOIKftFbDTJ4DvWa8cbnZlK9HHrn7lhXwvmCY0FkvL9dtD0azgJkwYRMGyOAqDMTk6S1oV04ZjAlbQgmtoldiAtkIJez6uZV3AdBzm0UnOD8O0sIhtRHfCAGxiAcT5oANfCD+YpJ7c4LPAetX/OaU40cLSVU1dA6YNAB5hZoqJ5h54W6gf6NEK5zkHclDsSO9oeyxkeirNAeL83GdLmX76PAAtQkr4H5K6S9ZnGd5at7HxRdZ5KuGElmwYwMxsWBOxZFl8glQ4UgAIX7TWopUYxZNNmYtTl1GwPJA+UyYfu60ryX6YOic3H/s9GUADqq/7ahKvnWa6iRa0+xkdy+GrrJMQOmBoCHzUGECDeu+N1JEcuHGnMy+bDSsGG6mz5dQT+VqdVcqosnGesobeuGOswAA2yW9rc/I4s7i9zGRzOD5u+xE/topYstqXZ3PYUgjzTi1V3pTwgBf5SSJYaxIap1s7nupZ86CjU3hvCdjcEQ69b3zYmKSjsGJ6+deL+C17CYYBqqUllYce2a/LoAwB4d1wGQ8vu8gwhyaI+tg2z0PZDGae21rF2ahYueOOd8W4nuqPuxtOUE80g3S3iYGKkctLNM/iWB/HFRyykg/Go/vllL1tapqfW2d5YGihXMO/iy4vtXaxA8pGKcnrcX8dvb8ufQt59w== core"
                  ]
                }
              ]
            },
            "storage": {
              "files": [
                {
                  "path": "/etc/profile.d/systemd-pager.sh",
                  "contents": {
                    "compression": "",
                    "source": "data:,%23%20Tell%20systemd%20to%20not%20use%20a%20pager%20when%20printing%20information%0Aexport%20SYSTEMD_PAGER%3Dcat%0A"
                  },
                  "mode": 420
                }
              ]
            },
            "systemd": {
              "units": [
                {
                  "enabled": false,
                  "name": "zincati.service"
                },
                {
                  "dropins": [
                    {
                      "contents": "[Service]\n# Override Execstart in main unit\nExecStart=\n# Add new Execstart with `-` prefix to ignore failure`\nExecStart=-/usr/sbin/agetty --autologin core --noclear %I $TERM\n",
                      "name": "autologin-core.conf"
                    }
                  ],
                  "name": "serial-getty@ttyS0.service"
                }
              ]
            }
          }
    spec:
      domain:
        features:
          smm:
            enabled: true
        firmware:
          bootloader:
            efi:
              persistent: true
        devices:
          tpm:
            persistent: true
          disks:
          - name: containerdisk
            disk:
              bus: virtio
          rng: {}
        resources:
          requests:
            memory: 4096M
      volumes:
      - name: containerdisk
        containerDisk:
          image: "quay.io/confidential-clusters/fedora-coreos-kubevirt:latest"
          imagePullPolicy: Always
